name: Notify Docusaurus of Markdown Changes

on:
  push:
    paths:
      - "README.md"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docusaurus rebuild
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.DOCUS_REPO_TOKEN }}" \
          https://api.github.com/repos/DaniellaAlolo/auth-docs/dispatches \
          -d '{"event_type": "external-doc-update"}'
